# This file stores configurations for your Shopify app.

scopes = 'read_products, read_discounts, write_customers, read_orders, write_orders, read_shipping, read_inventory, write_inventory, read_fulfillments, write_fulfillments, read_locations'